POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Christian Gomez 1",
    "number": "11224455"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Christian Gomez"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{   
    "number": "11224455"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{   
   
}

